server:
  port: ${port:8080}

logging:
  level:
    org.springframework.web: WARN
    com.test: TRACE

spring:
  profiles:
    active: with-rpc

rabbitmq:
  host: localhost
  exchange:
    log:
      name: logs
      type: fanout
  queue:
    rpc:
      name: rpc_queue